
import{Perfil} from '../modelo/perfin.model'

export const Cantantes:Perfil[]=[
    {
        id:1,
        nombre:'Edwans',
        apellido:'Silvio',
        img:'../../assets/img/img_cantante/edwans.jpg',
        edad:25,
        sexo:true,
        pais:'URU',
        profecion:'Cantante'
    },
    {
        id:3,
        nombre:'Justin',
        apellido:'Beber',
        img:'../../assets/img/img_cantante/justin_biber.jpg',
        edad:17,
        sexo:true,
        pais:'BRA',
        profecion:'Cantante'
    },
    {
        id:4,
        nombre:'Maicol',
        apellido:'Jason',
        img:'../../assets/img/img_cantante/maicol_Jason.jpg',
        edad:35,
        sexo:true,
        pais:'ARG',
        profecion:'Cantante'
    },
    {
        id:5,
        nombre:'Ricki',
        apellido:'Martin',
        img:'../../assets/img/img_cantante/ricki_martin.jpg',
        edad:32,
        sexo:true,
        pais:'ARG',
        profecion:'Cantante'
    },
    {
        id:6,
        nombre:'Selena',
        apellido:'Gomes',
        img:'../../assets/img/img_cantante/selena_gomes.jpg',
        edad:17,
        sexo:false,
        pais:'BRA',
        profecion:'Cantante'
    },
]
export const Futbolistas:Perfil[]=[
    {
        id:1,
        nombre:'maycol',
        apellido:'Gomes',
        img:'../../assets/img/img_futbol/hm1.jpg',
        edad:8,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:2,
        nombre:'Samuel',
        apellido:'Gimenes',
        img:'../../assets/img/img_futbol/hm2.jpg',
        edad:12,
        sexo:true,
        pais:'URU',
        profecion:'futbolista'
    },
    {
        id:3,
        nombre:'messi',
        apellido:'Taco',
        img:'../../assets/img/img_futbol/hy1.jpg',
        edad:32,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:4,
        nombre:'Rickelmes',
        apellido:'Santos',
        img:'../../assets/img/img_futbol/hy2.jpg',
        edad:30,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:5,
        nombre:'Maria',
        apellido:'Flores',
        img:'../../assets/img/img_futbol/mm1.jpg',
        edad:18,
        sexo:false,
        pais:'BRA',
        profecion:'futbolista'
    },
    {
        id:6,
        nombre:'Mayra',
        apellido:'sua',
        img:'../../assets/img/img_futbol/mm2.png',
        edad:12,
        sexo:false,
        pais:'BRA',
        profecion:'futbolista'
    },
    {
        id:7,
        nombre:'Jimena',
        apellido:'Ruis',
        img:'../../assets/img/img_futbol/mm3.png',
        edad:15,
        sexo:false,
        pais:'URU',
        profecion:'futbolista'
    },
    {
        id:8,
        nombre:'Daiana',
        apellido:'Ruiz',
        img:'../../assets/img/img_futbol/my1.jpeg',
        edad:23,
        sexo:false,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:9,
        nombre:'silvia',
        apellido:'Son',
        img:'../../assets/img/img_futbol/my2.jpg',
        edad:28,
        sexo:false,
        pais:'URU',
        profecion:'futbolista'
    },
]