
import{Detalles_sub_perfil, Perfil} from '../modelo/perfin.model'

export const Cantantes:Perfil[]=[
    {
        id:1,
        nombre:'Edwans',
        apellido:'Silvio',
        img:'../../assets/img/img_cantante/edwans.jpg',
        edad:25,
        sexo:true,
        pais:'URU',
        profecion:'Cantante'
    },
    {
        id:3,
        nombre:'Justin',
        apellido:'Beber',
        img:'../../assets/img/img_cantante/justin_biber.jpg',
        edad:17,
        sexo:true,
        pais:'BRA',
        profecion:'Cantante'
    },
    {
        id:4,
        nombre:'Maicol',
        apellido:'Jason',
        img:'../../assets/img/img_cantante/maicol_Jason.jpg',
        edad:35,
        sexo:true,
        pais:'ARG',
        profecion:'Cantante'
    },
    {
        id:5,
        nombre:'Ricki',
        apellido:'Martin',
        img:'../../assets/img/img_cantante/ricki_martin.jpg',
        edad:32,
        sexo:true,
        pais:'ARG',
        profecion:'Cantante'
    },
    {
        id:6,
        nombre:'Selena',
        apellido:'Gomes',
        img:'../../assets/img/img_cantante/selena_gomes.jpg',
        edad:17,
        sexo:false,
        pais:'BRA',
        profecion:'Cantante'
    },
]
export const Futbolistas:Perfil[]=[
    {
        id:1,
        nombre:'maycol',
        apellido:'Gomes',
        img:'../../assets/img/img_futbol/hm1.jpg',
        edad:8,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:2,
        nombre:'Samuel',
        apellido:'Gimenes',
        img:'../../assets/img/img_futbol/hm2.jpg',
        edad:12,
        sexo:true,
        pais:'URU',
        profecion:'futbolista'
    },
    {
        id:3,
        nombre:'messi',
        apellido:'Taco',
        img:'../../assets/img/img_futbol/hy1.jpg',
        edad:32,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:4,
        nombre:'Rickelmes',
        apellido:'Santos',
        img:'../../assets/img/img_futbol/hy2.jpg',
        edad:30,
        sexo:true,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:5,
        nombre:'Maria',
        apellido:'Flores',
        img:'../../assets/img/img_futbol/mm1.jpg',
        edad:18,
        sexo:false,
        pais:'BRA',
        profecion:'futbolista'
    },
    {
        id:6,
        nombre:'Mayra',
        apellido:'sua',
        img:'../../assets/img/img_futbol/mm2.png',
        edad:12,
        sexo:false,
        pais:'BRA',
        profecion:'futbolista'
    },
    {
        id:7,
        nombre:'Jimena',
        apellido:'Ruis',
        img:'../../assets/img/img_futbol/mm3.png',
        edad:15,
        sexo:false,
        pais:'URU',
        profecion:'futbolista'
    },
    {
        id:8,
        nombre:'Daiana',
        apellido:'Ruiz',
        img:'../../assets/img/img_futbol/my1.jpeg',
        edad:23,
        sexo:false,
        pais:'ARG',
        profecion:'futbolista'
    },
    {
        id:9,
        nombre:'silvia',
        apellido:'Son',
        img:'../../assets/img/img_futbol/my2.jpg',
        edad:28,
        sexo:false,
        pais:'URU',
        profecion:'futbolista'
    },
]
export const Detalles_Cantantes:Detalles_sub_perfil[]=[
    {
        id:1,
        titulo:'pop',
        añoPublicado:2012,
        img:'https://www.educaciontrespuntocero.com/wp-content/uploads/2019/10/music.jpg',        
        perfonaje:1,
    },
    {
        id:2,
        titulo:'Electronica',
        añoPublicado:2015,
        img:'https://i.ytimg.com/vi/5xipODON0-U/maxresdefault.jpg',       
        perfonaje:1,
    },
    {
        id:3,
        titulo:'pop 2',
        añoPublicado:2016,
        img:'https://previews.123rf.com/images/bluebay/bluebay1503/bluebay150300027/37297785-mundo-digital-con-auriculares-el-concepto-de-m%C3%BAsicas-del-mundo.jpg',
        perfonaje:2,
    },
    {
        id:4,
        titulo:'pianista',
        añoPublicado:2010,
        img:'https://www.definicionabc.com/wp-content/uploads/musica-332x500.jpg',
        perfonaje:2,
    },
    {
        id:5,
        titulo:'Guitarra',
        añoPublicado:2009,
        img:'https://i.ytimg.com/vi/B9g9SRUSGaE/maxresdefault.jpg',
        perfonaje:3,
    },
    {
        id:6,
        titulo:'musica latina',
        añoPublicado:2008,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9YetMVuFCoAb-sIcH0SKdDney5gdy96frzA&usqp=CAU',
        perfonaje:3,
    },
    {
        id:7,
        titulo:'pal mundo',
        añoPublicado:2011,
        img:'https://lh3.googleusercontent.com/proxy/kjYW2rs8B6Mdk30dHTUYQyWigNR-pXf-qaChQrpTa2nBZbh6BCX2qRBcMaCl6DtkRaGLqD03vZ_LjbNiEzrgPWzDRnAdwVFLYbTGeYYy_gjoxC0nClNvld9DoqEMWUnrDIquDocyIidx7m8xS_QY6_slRjAQ',
        perfonaje:3,
    },
    {
        id:8,
        titulo:'latino',
        añoPublicado:0,
        img:'https://fmradiokiss.radio12345.com/users.img/3160245/7/18/2043306844125.thumb.jpg',
        perfonaje:4,
    },
    {
        id:9,
        titulo:'musica de fondo',
        añoPublicado:2003,
        img:'https://i.ytimg.com/vi/Gjk20g2qNvc/maxresdefault.jpg',        
        perfonaje:4,
    },
    {
        id:10,
        titulo:'ling line',
        añoPublicado:2020,
        img:'https://www.inglesdenuevayork.com/wp-content/uploads/2016/03/Las-6-m%C3%BAsicas-perfectas-para-aprender-ingl%C3%A9s-cantando.jpg',
        perfonaje:1,
    },
    {
        id:11,
        titulo:'viva la vida',
        añoPublicado:2014,
        img:'https://i.pinimg.com/originals/27/c0/ce/27c0ce8e1b4b241ef8a401de6e553b49.jpg',        
        perfonaje:2,
    },
    {
        id:12,
        titulo:'un buen cambio',
        añoPublicado:2016,
        img:'https://promocionmusical.es/wp-content/uploads/2018/07/consumidor-de-musica.jpg',        
        perfonaje:3,
    },
    {
        id:13,
        titulo:'cha cha cha',
        añoPublicado:2001,
        img:'https://cdni.rbth.com/rbthmedia/images/web/es-rbth/images/2015-09/top/rian_02536086_673.jpg',        
        perfonaje:4,
    },
    {
        id:14,
        titulo:'clasicos 80',
        añoPublicado:1980,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxkR0Gw2uyax9J3ikBeLTCdRR0JbjBEDzIGQ&usqp=CAU',      
        perfonaje:3,
    },
    {
        id:15,
        titulo:'Romanticas',
        añoPublicado:2018,
        img:'https://i.ytimg.com/vi/zg2JNxnr2nM/maxresdefault.jpg',       
        perfonaje:2,
    },
    {
        id:16,
        titulo:'Muisic Android',
        añoPublicado:2021,
        img:'https://www.oficinadanet.com.br/imagens/post/17733/capa-android-musica.jpg',
        perfonaje:1,
    },
    {
        id:17,
        titulo:'trofeo global',
        añoPublicado:2021,
        img:'https://i.blogs.es/9258e0/trofeos-01/1366_2000.jpeg',
        perfonaje:1,
    },

]
export const Detalles_Futbool:Detalles_sub_perfil[]=[
   
    {
        id:1,
        titulo:'trofeo global',
        añoPublicado:2021,
        img:'https://i.blogs.es/9258e0/trofeos-01/1366_2000.jpeg',
        perfonaje:1,
    },
    {
        id:2,
        titulo:'trofeo mundial',
        añoPublicado:1010,
        img:'https://image.freepik.com/vector-gratis/trofeo-dorado-realista-espacio-texto_48799-1062.jpg',
        perfonaje:2,
    },
    {
        id:3,
        titulo:'trofeo campal',
        añoPublicado:2015,
        img:'https://http2.mlstatic.com/D_NQ_NP_837193-MLA29129791189_012019-O.jpg',
        perfonaje:3
    },
    {
        id:4,
        titulo:'trofeo Amistad',
        añoPublicado:2000,
        img:'https://img.freepik.com/vector-gratis/trofeo-oro-placa-ganador-concurso_68708-545.jpg?size=338&ext=jpg',
        perfonaje:4,
    },
    {
        id:5,
        titulo:'trofeo nacional',
        añoPublicado:2016,
        img:'https://static.vecteezy.com/system/resources/previews/000/619/954/non_2x/realistic-golden-silver-and-bronze-trophies-with-gold-laurel-wreath-and-ribbon-vector-illustration.jpg',
        perfonaje:5,
    },
    {
        id:6,
        titulo:'trofeo Capital',
        añoPublicado:2019,
        img:'http://mensajeconpoder.net/wp-content/uploads/2019/07/el-trofeo-de-lal-vida-eterna-300x300.jpg',
        perfonaje:6,
    },
    {
        id:7,
        titulo:'trofeo Junior',
        añoPublicado:2005,
        img:'https://previews.123rf.com/images/yupiramos/yupiramos1702/yupiramos170203479/70843626-establecer-premios-trofeos-medallas-ilustraci%C3%B3n-vectorial-de-dise%C3%B1o.jpg',
        perfonaje:7,
    },
    {
        id:8,
        titulo:'Trofeo Juvenil',
        añoPublicado:2017,
        img:'https://lh3.googleusercontent.com/proxy/FVbtdI9u16cyCmxZsiZ02UMTNywS7tl8Ikwm3xUblFPCkBHm84YasaqvtmkZubTwZVpcDYt66R_NqAm1ZU2ZtNYu5QV74p-ZylUWCou-nbwKERMcxbdLOPMwRr9_rN0',
        perfonaje:8,
    },
    {
        id:9,
        titulo:'trofeo multinacional',
        añoPublicado:2016,
        img:'https://st1.uvnimg.com/d3/e9/4add382b4e4ba78af5245e55765b/trofeos-futbol.jpg',
        perfonaje:9,
    },
    {
        id:10,
        titulo:'copa internacional',
        añoPublicado:1021,
        img:'https://static.brusheezy.com/system/resources/previews/000/060/992/non_2x/20-trophy-cup-ps-brushes-abr-vol-15.jpg',
        perfonaje:3,
    },
    {
        id:11,
        titulo:'copa mundial',
        añoPublicado:2021,
        img:'https://i.pinimg.com/originals/f6/d5/a5/f6d5a574e0d747f18b4f8dd046e781dc.jpg',
        perfonaje:2,
    },
    {
        id:12,
        titulo:'copas ganas',
        añoPublicado:2022,
        img:'https://i1.wp.com/www.gameoverla.com/wp-content/uploads/2020/10/ps5-trophies-will-finally-get-a-progress-tracker-1024x578.jpg?fit=1024%2C578&ssl=1',
        perfonaje:3,
    },

]